apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securing-web-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/NguyenPhuongThao05/PhatTrienUDDN.git
    targetRevision: HEAD
    path: secure/k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: securing-web-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true